Updated dependency
opentracing-contrib/csharp-grpc pull request #13
Opened 2019-10-21 12:24 UTC by iEmiya

Make necessary changes to build project under .NET Framework 4.6.1 & .Net Core 2.1, as well as updated links:
* Google.Protobuf 3.5.1 to 3.10.0
* Grpc 1.12.0 to 2.24.0

2019-10-24 09:21 UTC, Falco20019 requested changes
Why was it necessary to change it into two projects? This project should only target .NET Standard and neither .NET Framework nor .NET Core to be also usable with Xamarin. Your changes would break this compatability.

If there is something limiting you due to .NET Standard 1.5 (in respect to dependencies) I would suggest upgrading it to .NET Standard 2.0 instead as this is still allowing usage with .NET Framework 4.6.1+ and .NET Core 2.0+ according to https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md

Since this is a library, we also should use only the minimum required version of the dependencies since this is a transitive minimum. The application using the NuGET package can always use newer version. As long as Google.Protobuf 3.10.0 has no breaking changes over 3.5.1, it should not be updated in a library. We definetly need to update Grpc to 2.23.0 as minimal requirement.

Please let me know your requirements and maybe it's better to create an issue ticket with those to see what's the best solution.

2019-10-24 09:21 UTC, Falco20019 commented on src/OpenTracing.Contrib.Grpc/netcore/OpenTracing.Contrib.Grpc.netCore.csproj
> +    <RepositoryUrl>git://github.com/Medialogia/csharp-grpc</RepositoryUrl>
This should point to https://github.com/opentracing-contrib/csharp-grpc

2019-10-28 10:22 UTC, iEmiya commented
> Why was it necessary to change it into two projects? This project should only target .NET Standard and neither .NET Framework nor .NET Core to be also usable with Xamarin. Your changes would break this compatability.
> 
> If there is something limiting you due to .NET Standard 1.5 (in respect to dependencies) I would suggest upgrading it to .NET Standard 2.0 instead as this is still allowing usage with .NET Framework 4.6.1+ and .NET Core 2.0+ according to https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md
> 
> Since this is a library, we also should use only the minimum required version of the dependencies since this is a transitive minimum. The application using the NuGET package can always use newer version. As long as Google.Protobuf 3.10.0 has no breaking changes over 3.5.1, it should not be updated in a library. We definetly need to update Grpc to 2.23.0 as minimal requirement.
> 
> Please let me know your requirements and maybe it's better to create an issue ticket with those to see what's the best solution.

In our projects we use projects under .NET Framework 4.6.1 and .NET Core 2.1.
I think, it would be logical to add to assembly under .NET Standard 2.0, but assembly under .NET Framework 4.6.1 gets rid of significant amount of dependent DLL platform during installation and deployment of Windows Service.

2019-10-31 06:33 UTC, Falco20019 commented
Understood :) For greater compatibility I will add .NET Framework 4.5 DLL to NuGET in #15 which should be usable without any additional DLLs in 4.6.1

2020-01-10 18:44 UTC, pcwiese commented
what happened with this change?

2020-01-10 21:37 UTC, Falco20019 commented
I haven’t had time lately for this project. Will try to look into it next week since the blocker should be resolved for some time now. Thanks for bringing it to my attention again.

2020-01-15 08:17 UTC, Falco20019 commented
Closed because superseeded by #13

2020-01-15 08:17 UTC, closed without merging